* Greap
=====

This is a repository to host the Greap, a project using the LeapMotion device.
To use this you need to download a latest stable version of SuperCollider, and GECO.
GECO is used to map out the Leap's data into SuperCollider. At the time of development of Greap GECO didn't support OSC, currently the software is using MIDI protocol.

Gr(ain) + (L)eap = Greap. Greap is an interactive music environment made to create live electroacoustic music. It started as a research project to investigate the gestural manipulation of sound events, and explore the affordances of open air interfaces. The idea was originally conceived by the need to shape sounds in real time using hands.

*** Installation
- Download SC from here:http://supercollider.sourceforge.net/

- GECO can be found at LeapMotion's AirSpace:https://airspace.leapmotion.com/

- Put the "dependancies" folder inside the "Extensions" folder of SuperCollider (create if it doesn't exist).
  * restart or recompile SuperCollider

* TODO
Make GECO <> SC communicate via OSC protocol (as of now GECO supports OSC).
