* Greap
=====

This is a repository to host Greap (vanilla), a project using the LeapMotion device.
To use, you need to download a latest stable version of SuperCollider, and GECO.
GECO is used to map out the Leap's data into SuperCollider. At the time of development of Greap GECO didn't support OSC, currently the software is using MIDI protocol.

Gr(ain) + (L)eap = Greap. /Greap/ is an interactive music environment made to create live electroacoustic music. It started as a research project to investigate the gestural manipulation of sound events, and explore the affordances of open air interfaces. The idea was originally conceived by the need to shape sounds using hands.
Note: This is a basic version of Greap and  provides very basic feautures. Gradually developing a full feature to release.

*** Usage
- Download the zip folder or clone Greap on your computer.
- Download SC from here:http://supercollider.sourceforge.net/

- GECO can be found at LeapMotion's AirSpace:https://airspace.leapmotion.com/

*** Run
- Open Greap.scd file in SuperCollider and execute the whole file.
+ This should open GECO and run the GECOMapper file automatically.

* TODO
*** To do list
- Make GECO <> SC communicate via OSC protocol (as of now GECO supports OSC).
- Support the dynamic alteration of the sound file during performing.
