* Greap
=====

This is a repository to host Greap (vanilla), a project using the LeapMotion device.
To use, you need to download a latest stable version of SuperCollider, and GECO.
GECO is used to map out the Leap's data into SuperCollider. At the time of development of Greap GECO didn't support OSC, currently the software is using MIDI protocol.

Gr(ain) + (L)eap = Greap. /Greap/ is an interactive music environment made to create live electroacoustic music. It started as a research project to investigate the gestural manipulation of sound events, and explore the affordances of open air interfaces. The idea was originally conceived by the need to shape sounds using hands.


*** Installation
- Download the zip folder or clone Greap on your computer.
- Download SC from here:http://supercollider.sourceforge.net/

- GECO can be found at LeapMotion's AirSpace:https://airspace.leapmotion.com/

- Put the "dependancies" folder (found on the zip folder you downloaded) and move it inside the "Extensions" folder of SuperCollider (create if it doesn't exist).
  * restart or recompile SuperCollider

*** Step by Step guide
1) Go to /Greap/GECOScript folder and run the GECOMapSC.geco document. This should start GECO.
2) Once you get GECO up and running, run the Greap.scd found in /Greap/GreapCode. This should start SuperCollider.
**** follow the order as noted.

* TODO
*** To do list
1. Make GECO <> SC communicate via OSC protocol (as of now GECO supports OSC).
